### ISSUE TITLE
Scrolling & relative resizing

### ISSUE THREAD

**Issue by Ento0n** [IvoLeist/dash_ngl#26]
Hello,
I love your tool and am currently working on my bachelor thesis with it, but the browser scrolls when zooming in or out and resizing of the viewer  relative to the browser size would be really neat.

Are there any plans on updating this?

**Comment by IvoLeist** [comment]
Hello Ento0n,

so cool to see that  someone is actually using it!
Unfortunately I cannot help you with it because it was only a Corona lockdown side project in between
my master and the start of my PhD :laughing: 

In my PhD I no longer work with Dash so I am way too out of it to help you...

BUT, I am very happy that at one point it got merged into DashBio.
It lives now on under the name NglMoleculeViewer:
https://dash.plotly.com/dash-bio/nglmoleculeviewer
*I should at least update the README :smile: 

So try your luck by opening an issue there :crossed_fingers: 
https://github.com/plotly/dash-bio 

If you are a programmer and find a fix do not hesitate to open a PR
The plotly devs are very supportive :)

All the best for your thesis!
Greeting from Barcelona :v:

**Comment by IvoLeist** [comment]
Actually I just played with the documentation and have seen what you are describing here.

This is definitely annoying :laughing:  but should be for you or the plotly devs an "easy" fix
since this behavior could be prevented by overwriting the `stage.mouseControls`
of the core ngl viewer see below under Mouse:
https://nglviewer.org/ngl/api/manual/interaction-controls.html

For example: 
`stage.mouseControls.add("scroll-shift", NGL.MouseActions.zoom);`

So with that in the viewer it will be only zoomed if the shift key is pressed while using the scroll wheel.

**Comment by Ento0n** [comment]
Hello Ivo,
thank you for your fast reply and your help. ((:

I see that the project is frozen for you but I will try my luck there!

I am a programmer studying bioinformatics, but NEVER got in touch with front end development up to my bachelor thesis project now. That's why I simply couldn't find a fast fix myself.

Therefore thank you very much for your more detailed help with the mouse controls. 

Greetings from munich :v:

**Comment by IvoLeist** [comment]
Hello EntoOn, 

if you are interested in Frontend Development, actually Dash(Bio) is a good way to start.
At least for me this was my first real contact with React.js.

If the DashBio dev environment set up has not changed to much I could give you a quick run down 
how to get started (in case you are interested/have time to fix it on your own? ;D)
I guess the easiest to set up a quick call is via 
[![](https://img.shields.io/twitter/follow/ivoleist.svg)](https://twitter.com/intent/follow?screen_name=ivoleist)

Btw. shameless plug but if you are interested to do an internship, your Master Thesis or a Junior Dev position
in Barcelona :sunglasses:  add https://www.cnag.crg.eu/jobs to your bookmarks we will publish multiple positions soonish :rocket:
